### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by byte-chan** [Gonow32/Impulse#3]
note for all files: we should sprinkle pcall all over them
- [x] FloppyLoader  
  FloppyLoader:6: code should probably `break` after finding a drive  
  FloppyLoader:21: math.ceil(w/2)-math.floor(#string/2) to make sure it's centered (suggestion)  
  FloppyLoader:52: safety check to prevent crashing if it's an Aurora game, probably a pcall?  
  FloppyLoader:80: safety check to prevent crashing if it's an Aurora game, probably a pcall?
- [x] credplay  
  credplay:5: add 0? (totally stupid suggestion)  
  credplay:35: see FloppyLoader:21
- [x] firstRun  
  firstRun:11: you should know by now, FloppyLoader:21  
  firstRun: too many else returns, wow
- [ ] gamelib
- [ ] gui
- [ ] help
- [ ] info
- [ ] music
- [ ] startup
- [ ] uibuild
- [ ] update
- [ ] apis
  - [ ] Impulse
  - [ ] tableMap
- [ ] menu
  k i can die now, you go review the code yourself

**Comment by Gonow32** [comment]
Look at things like the Impulse system library, it is full of pcall!

**Comment by byte-chan** [comment]
k
